[book]
src = 'src'
title = 'Pxswap'
[output.html]
no-section-label = true
additional-js = ['solidity.min.js']
additional-css = ['book.css']
git-repository-url = 'https://github.com/pxswap-xyz/pxswap'

[output.html.fold]
enable = true
